name: Scrape Pinterest Boards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"  # runs daily at 4 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pinterest board scraper
        run: python scripts/scrape_boards.py

      - name: Commit and push JSON output
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output/boards.json
          git commit -m "Update Pinterest board list" || echo "No changes"
          git push
