name: Scrape Pinterest Boards

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium

      - name: Run Scraper
        run: python .github/scripts/scrape_pinterest_board_names.py

      - name: Upload JSON Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pinterest-boards
          path: pinterest_boards.json
